### ISSUE TITLE
Issuesの運用方法検討

### ISSUE THREAD

**Issue by W-Muro** [W-Muro/workflow-for-solo-development#2]
- [x] ラベル名を決める
- [x]  issue templatesの作成
- [x] タスクばらしを考察
- [x] Issueタイトル（ブランチ名）の決め方
- 英語？日本語？イシュー番号だけ？
- ルールはどうする？
- プレフィックスや階層化（issues/task）はどうする？

**Comment by watt-jpn** [comment]
ブランチ名は"issues/#<issue_number>"で統一する。
