### ISSUE TITLE
PRの運用方法検討

### ISSUE THREAD

**Issue by W-Muro** [W-Muro/workflow-for-solo-development#4]
- [x] 01. SettingsにあるPRルールについて検討
- [x] 02. WIP PRとDraft PRについて調べる

**Comment by watt-jpn** [comment]
### 01. SettingsにあるPRルールについて検討
- PRのマージは"Marge pull request"のみ
   squashやrebaseは使用しないので"Settings > General > Pull Requests"でチェックを外す

参考：[ワイのGitHubリポジトリおすすめ設定(2022年 決定版)](https://qiita.com/john-Q/items/8b42d56b0be4ec63edb4#113-pull-requests)
